spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
      database: MySQL
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
